const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.ScriptsInEvents.Jogo_Event12_Act2
	];
};
self.C3_JsPropNameTable = [
	{FundoInicio: 0},
	{FundoJogo: 0},
	{Sólido: 0},
	{chao: 0},
	{Projétil: 0},
	{Meteoro: 0},
	{carne: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{dino: 0},
	{Mouse: 0},
	{Teclado: 0},
	{placar: 0},
	{Texto: 0},
	{titulo: 0},
	{Play: 0},
	{Áudio: 0},
	{restart: 0},
	{BTNhome: 0},
	{history: 0},
	{Sprite2: 0},
	{PlanoDeFundoEmBlocos: 0},
	{pronto: 0},
	{placarGOver: 0},
	{ScoreGOver: 0},
	{pontos: 0}
];

self.InstanceType = {
	FundoInicio: class extends self.ISpriteInstance {},
	FundoJogo: class extends self.ISpriteInstance {},
	chao: class extends self.ITiledBackgroundInstance {},
	Meteoro: class extends self.ISpriteInstance {},
	carne: class extends self.ISpriteInstance {},
	dino: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	placar: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	titulo: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	restart: class extends self.ISpriteInstance {},
	BTNhome: class extends self.ISpriteInstance {},
	history: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	pronto: class extends self.ISpriteInstance {},
	placarGOver: class extends self.ISpriteInstance {},
	ScoreGOver: class extends self.ITextInstance {}
}